language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean install -pl "!:che-dashboard-war"
#addons:
#  apt:
#    packages:
#      - check
#      - libcppunit-dev
#before_install:
#- 